export const data = [
  {
    id: "1",
    "Nama Lengkap": "Rina Ayu",
    "Status Penghuni": "kontrak",
    "Nomor Telepon": "081234567890",
    "Status Perkawinan": "Belum menikah",
    fotoKTP: "https://dummyimage.com/720x400",
  },
  {
    id: "2",
    "Nama Lengkap": "Budi Santoso",
    "Status Penghuni": "tetap",
    "Nomor Telepon": "085612345678",
    "Status Perkawinan": "Sudah menikah",
    fotoKTP: "https://dummyimage.com/720x400",
  },
  {
    id: "3",
    "Nama Lengkap": "Siti Nurhaliza",
    "Status Penghuni": "kontrak",
    "Nomor Telepon": "082134567899",
    "Status Perkawinan": "Sudah menikah",
    fotoKTP: "https://dummyimage.com/720x400",
  },
  {
    id: "4",
    "Nama Lengkap": "Agus Wijaya",
    "Status Penghuni": "tetap",
    "Nomor Telepon": "081356789012",
    "Status Perkawinan": "Sudah menikah",
    fotoKTP: "https://dummyimage.com/720x400",
  },
  {
    id: "5",
    "Nama Lengkap": "Dewi Lestari",
    "Status Penghuni": "kontrak",
    "Nomor Telepon": "083867890123",
    "Status Perkawinan": "Belum menikah",
    fotoKTP: "https://dummyimage.com/720x400",
  },
];
