export const data = [
  {
    id: "1",
    "Nama Rumah": "Rumah A1",
    "Nama Pembayar": "Rina Ayu",
    "Bulan": "Januari",
    "Tahun": "2025",
    "Jenis Iuran": "Kebersihan",
    "Tagihan": "100000",
    "Status Pembayaran": "Lunas",
  },
  {
    id: "2",
    "Nama Rumah": "Rumah B2",
    "Nama Pembayar": "Budi Santoso",
    "Bulan": "Februari",
    "Tahun": "2025",
    "Jenis Iuran": "Keamanan",
    "Tagihan": "120000",
    "Status Pembayaran": "Belum Lunas",
  },
  {
    id: "3",
    "Nama Rumah": "Rumah C3",
    "Nama Pembayar": "Siti Nurhaliza",
    "Bulan": "Maret",
    "Tahun": "2025",
    "Jenis Iuran": "Kebersihan",
    "Tagihan": "90000",
    "Status Pembayaran": "Lunas",
  },
  {
    id: "4",
    "Nama Rumah": "Rumah D4",
    "Nama Pembayar": "Agus Wijaya",
    "Bulan": "April",
    "Tahun": "2025",
    "Jenis Iuran": "Keamanan",
    "Tagihan": "130000",
    "Status Pembayaran": "Belum Lunas",
  },
  {
    id: "5",
    "Nama Rumah": "Rumah E5",
    "Nama Pembayar": "Dewi Lestari",
    "Bulan": "Mei",
    "Tahun": "2025",
    "Jenis Iuran": "Kebersihan",
    "Tagihan": "110000",
    "Status Pembayaran": "Lunas",
  },
];
